openapi: 3.0.1
info:
  title: Header_API
  description: API Definition of Header_API
  version: 1.0.0
servers:
- url: http://localhost:8290/test
paths:
  /:
    post:
      responses:
        default:
          description: Default response
